version: '3'

services: 
    redisdb:
        image: redis:5.0.0
        container_name: redisdb
        ports: 
            - 6379:6379

    nodeapp1:
        build: .
        container_name: nodeapp1
        ports: 
            - 5001:3000
        depends_on: 
            - redisdb
        environment: 
            - REDIS_HOST=redisdb
    
    nodeapp2:
        build: .
        container_name: nodeapp2
        ports: 
            - 5002:3000
        depends_on: 
            - redisdb
        environment: 
            - REDIS_HOST=redisdb

    nginx:
        image: nginx:latest
        container_name: nginx
        ports: 
            - 8080:8080 
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on: 
            - nodeapp1
            - nodeapp2